import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.scss";
import "antd/dist/reset.css";
import StyledComponentsRegistry from "../utils/AntdRegistry";
import Nav from "../components/nav/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
